version: '3.9'
services:
  api:
    image: ghcr.io/santhoshkumarvs/neuralcura-api:latest
    ports:
      - "80:8000"
    env_file:
      - .env.prod
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    restart: always
