name: Deploy to Production

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/neuralcura-api:latest .
        docker push ghcr.io/${{ github.repository }}/neuralcura-api:latest

    - name: Deploy via SSH to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_KEY }}
        script: |
          docker pull ghcr.io/${{ github.repository }}/neuralcura-api:latest
          docker-compose -f docker-compose.prod.yml up -d